derekkraan/horde

lib/horde/registry.ex
lib/horde/supervisor_impl.ex
lib/horde/uniform_distribution.ex
lib/horde/uniform_quorum_distribution.ex
mix.exs
mix.lock
test/uniform_distribution_test.exs
test/uniform_quorum_distribution_test.exs

Fix reconnection issue.
What was happening:
If you connected to a horde, disconnected, and then connected again, things were going wrong.
Internally, the delta_crdt maintains a list of neighbours, and a map of neighbours to ack'ed deltas. The reference used for a neighbour was in this case of the form `{HelloWorld.HelloSupervisor, :"hello1@127.0.0.1"}` (in the case of the example app). The problem is: if this process were to die and be restarted, the reference would not change, so the neighbours would not send in the correct deltas.
The solution is to only communicate using pids. So now the neighbours list is a simple list of pids. This ensures that when these processes (or the entire node) are restarted, that the reference in the neighbours list is new.

Fix connection issue

---

lib/horde/registry.ex

I had to do this to address https://github.com/derekkraan/horde/issues/16 because I shut down registries often (when nodes go away). I know you're refactoring this module, so this may change or go away, but I wanted to make sure you knew.

Trap exits in registry process so terminate gets called more reliably

---

lib/horde/registry.ex

When checking if a process is alive, check whether its node is visible before running an rpc on it. This lets the check fail fast if the node has been disconnected. We want this check to be fast since it is used by `Registry.lookup/2`. However, `:rpc.call/4` actually attempts to establish a connection if the node is not yet connected, and this could hang for a long time depending on the network state. (I run into this often when running on Kubernetes where I bring nodes up and down frequently.)

Precheck for node connection in Registry.process_alive?/1

---

lib/horde/cluster.ex

When using module name instead of pids, example:
```elixir
Enum.each(Node.list(), fn node ->
Horde.Cluster.join_hordes(
MyApp.DistributedRegistry,
{MyApp.DistributedRegistry, node}
)
end)
```
I encountered following dialyzer warnings (using dialyxir 1.0.0-rc.3)
```
lib/my_app/horde_connector.ex:29:call
The call:
Horde.Cluster.join_hordes(MyApp.DistributedRegistry, {MyApp.DistributedRegistry, _})
breaks the contract
(horde :: pid(), other_horde :: pid()) :: boolean()
```
This PR fixes this.

fixed dialyzer warnings caused by Horde.Cluster specs

---

examples/hello_world/mix.lock

The example app was referencing a previous version of xxhash which contained a bug that was fixed in the latest version. I discovered this while trying to run the hello world application. 
Updating to the latest version fixes the issue. 
Thanks for a great library. I am excited to play with it.

Update xxhash version 0.2.0 => 0.2.1 for the example "Hello World" application. 

---

examples/hello_world/README.md
examples/hello_world/lib/hello_world/application.ex
examples/hello_world/lib/hello_world/say_hello.ex

In the example we initialize the state of the `HelloWorld.SayHello` GenServer with the "count" value stored in `Horde.Registry` meta data. When `:say_hello` is received, we now also increment the "count" value. 
If the node running the single `HelloWorld.SayHello` instance is killed, and the supervisor starts a new instance, the state is read from the shared meta data and the counter continues where the previous instance of `SayHello` left off.

Update example app to share data across the Horde.

---

lib/horde/supervisor_supervisor.ex

I noticed that the default distribution_strategy in `SupervisorImpl` is Horde.UniformDistribution and that setting the `distritbution_strategy` in the options to `Horde.Supervisor` was not being passed through to allow one to override the `distribution_strategy` with something else. 
I think this change will allow that. It works for me locally.

Pass supervisor options through to SupervisorImpl

---

lib/horde/process_supervisor.ex

When child_id of a process is converted to a binary it is possible that its length exceeds the system limit of atom length so I used SHA1 to always create a fixed size identifier of any child_id.

Use sha1 to generate string identifier of a term

---

lib/horde/registry_impl.ex

```
warning: variable "value" is unused (if the variable is not meant to be used, prefix it with an underscore)
lib/horde/registry_impl.ex:188
```

fix warning

---

lib/horde/supervisor_impl.ex
test/cluster_test.exs

Using horde version 0.5-pre, starting a supervisor child after calling `Horde.Cluster.set_members/2` fails with the following error:
```
[error] GenServer :sup0 terminating                                
** (ArithmeticError) bad argument in arithmetic expression                      
:erlang.rem(1548551151, 0)                                                  
(horde) lib/horde/uniform_distribution.ex:17: Horde.UniformDistribution.choose_node/2                                                                       
(horde) lib/horde/supervisor_impl.ex:151: Horde.SupervisorImpl.handle_call/3
(stdlib) gen_server.erl:661: :gen_server.try_handle_call/4                  
(stdlib) gen_server.erl:690: :gen_server.handle_msg/6                       
(stdlib) proc_lib.erl:249: …
```

fix cannot start supervisor children after calling `set_members`

---

lib/horde/uniform_distribution.ex
test/uniform_distribution_test.exs

If all cluster members are in `:dead` or `:shutting_down` state, when `choose_node/2` is called an exception is raised because a division by zero is attempted.
This often happens in tests, because of the fast termination of cluster members (it happens in horde's supervisor tests too).
Here i added a return value of `{:error, :no_alive_nodes}` when no nodes are available, similar to what happens in the uniform quorum distribution case.
A test is added to expose the bug.

An exception is raised when `Horde.UniformDistribution.choose_node/2` and no alive members are available

---

lib/horde/registry.ex
test/registry_test.exs

Feature
Fixes: #101
As for `match/4`, this is a new function used to match on the keys instead.
No
@derekkraan Is there a code convention or a commit naming convention to respect? I would like to contribute more and looking to improve documentation.

Add registry select/4

---

lib/horde/registry.ex
test/registry_test.exs

This patch makes Registry.register/3 more in line with its Elixir
equivalent. In fact, I copied the test cases from Elixir's Registry.
Duplicate registrations can still happen (overwrite each other) within
members of the cluster. This will be dealt with in another PR

Registry: Prevent local duplicate registration

---

lib/horde/registry.ex
lib/horde/registry_impl.ex
test/registry_test.exs

When 2 clustered registries register the same name at exactly the  same time, it will seem like name registration succeeds for both  registries. The function returns `{:ok, pid}` for both of these  calls.
However, due to the eventual consistent nature of the CRDT, a  conflict resolution will take place, and the CRDT will pick one of  the two processes as the "winner" of the name. The losing process   will then receive a message to indicate that it has lost the name  registration. The message looks like this:
{:name_conflict, {name, value}, registry_name, winning_pid}

 Send :name_conflict message to losing process when registries merge

---

lib/horde/registry.ex

this fixes the typespecs to avoid dialyzer errors in projects using this library.

fix Registry specs

---

lib/horde/horde_dynamic_supervisor.ex
lib/horde/supervisor.ex
lib/horde/supervisor_impl.ex
test/supervisor_test.exs

This PR increases compatability with DynamicSupervisor.
Changes:
- `start_child/2` ignores any `id` in the child_sped argument, and generates its own id for internal use.
- `terminate_child/2` accepts a pid as second argument instead of an id
- `which_children/1` now returns `{:undefined, pid, type, modules}`
This PR should solve the following issues: #82, #54.
This PR also means `Horde.Supervisor` no longer dedups processes across a cluster. Just like `Elixir.DynamicSupervisor`, you're expected to use `Horde.Registry` to gain this functionality.

More compatible with DynamicSupervisor

---

CHANGELOG.md
lib/horde/registry.ex

Elixir.Registry and highlights the differences.

Improve Registry documentation. Documentation now refers to

---

lib/horde/registry_supervisor.ex
lib/horde/supervisor_supervisor.ex

Sending the diff might fail (with an ArgumentError) because on
shutdown, the supervisor is already stopped, and thus, the root name
is not registered anymore in the process registry.

Do not crash when trying to send a CRDT update to the root name

---

lib/horde/registry.ex
lib/horde/supervisor_impl.ex
test/mixed_test.exs

This will solve a race condition caused by a registry not being aware
that a remote process has died (eg, during node shut down)

Check if process alive on `Horde.Registry.register/3`.

---

lib/horde/supervisor_impl.ex
lib/horde/uniform_distribution.ex
mix.exs
test/supervisor_test.exs

With #122 we started assigning random ids to bring us in line with DynamicSupervisor's API. This broke consistent hashing. This PR restores that, by hashing the child spec minus the id.
Caveat: if you are starting processes that only differ by the id, and want them to end up on different nodes, then you will have to add something to the child_spec to differentiate them, or alternatively supply your own distribution_strategy.
Also removes xxhash as dependency.
_This PR needs a test._

Hash the child spec minus the id for consistent hashing.

---

lib/horde/uniform_distribution.ex
mix.exs
mix.lock
test/uniform_distribution_test.exs
test/uniform_quorum_distribution_test.exs

Should only merge once this PR has been merged: https://github.com/bitwalker/libring/pull/19
Solves #130

Use libring to distribute processes over nodes.

---

lib/horde/supervisor.ex
test/supervisor_test.exs
test/support/module_based_supervisor.ex

Make Horde.Supervisor child_spec overridable

---

lib/horde/registry.ex
test/registry_test.exs

What kind of change does this PR introduce?
**Bugfix**
We got a `MatchError`.
We can now register our process with metadata:
```elixir
{:ok, _} = Horde.Registry.start_link(keys: :unique, name: Horde.Registry.ViaTest)
name = {:via, Horde.Registry, {Horde.Registry.ViaTest, "agent", :hello}}
{:ok, _} = Agent.start_link(fn -> 0 end, name: name)
Horde.Registry.lookup(Horde.Registry.ViaTest, "agent")
#=> [{self(), :hello}]
```
**No**

Fix via register with meta

---

lib/horde/registry.ex
test/registry_test.exs
test/support/module_based_registry.ex
test/uniform_distribution_test.exs
test/uniform_quorum_distribution_test.exs

* `child_spec` configurable with inline options during `use` like for regular `GenServer`
* `child_spec` can be redefined and refined with `super`

Ensure Registry.child_spec/1 overridable.

---

guides/libcluster.md

@derekkraan We should also be adding our Registry to `set_members` here, correct? If so, I'll add this into the readme, so it will create less confusion for others.
```elixir
def handle_info({:nodeup, _node, _node_type}, state) do
set_members(MyHordeRegistry)
set_members(MyHordeSupervisor)
{:noreply, state}
end
def handle_info({:nodedown, _node, _node_type}, state) do
set_members(MyHordeRegistry)
set_members(MyHordeSupervisor)
{:noreply, state}
end
```
-- Shawn

update libcluster guide

---

guides/eventual_consistency.md

We encountered a small error in the guides. When trapping exits, the actual message is wrapped in an {:exit, from, reason} tuple.

handle_info :name_conflict with correct :EXIT match

---

CHANGELOG.md
guides/getting_started.md
lib/horde/registry.ex
lib/horde/supervisor.ex
test/cluster_test.exs
test/registry_test.exs
test/supervisor_test.exs

My fault, I didn't remember when I renamed `delta_crdt_options` to `delta_crdt` in my previous pull request, and it wasn't my intention.

Revert delta crdt options field naming

---

.gitignore
mix.exs
mix.lock
test/local_cluster_test.exs
test/support/worker.ex
test/test_helper.exs

As we spoke of on Slack.
I get this to fail _very_ sporadically locally. And there's also some weird output when the process starts, which makes it looks like it's initially starting twice on the same node.
```
12:28:09.927 [info]  Starting worker on :"cluster-3291@127.0.0.1"
12:28:09.927 [info]  Starting worker on :"cluster-3291@127.0.0.1"
12:28:09.927 [info]  Started worker on :"cluster-3291@127.0.0.1"
12:28:09.927 [info]  Started worker on :"cluster-3291@127.0.0.1"
```

Add netsplit test

---

.circleci/config.yml
test/netsplit_test.exs
test/support/my_supervision_tree.ex
test/test_helper.exs

This PR does not fix anything. It adds a net split/name conflict test case that, when run in a loop, either:
a. passes ok, without any errors.
b. passes, but produces a bunch of errors such as:
```
23:12:46.234 [error] GenServer MySupervisor terminating
** (stop) exited in: GenServer.stop(MySupervisor.ProcessesSupervisor, :normal, :infinity)
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
(elixir) lib/gen_server.ex:967: GenServer.stop/3
(horde) lib/horde/dynamic_supervisor_impl.ex:588: Horde.DynamicSupervisorImpl.shut_down_all_processes/1
(horde) lib/horde/dynamic_supervisor_impl.ex:568: Horde.DynamicSupervisorImpl.set_members/2
(horde) lib/horde/dynamic_supervisor_impl.ex:117: …
```

intermittently failing netsplit/name conflict test

---

guides/libcluster.md
lib/horde/dynamic_supervisor.ex
lib/horde/dynamic_supervisor_impl.ex
lib/horde/node_listener.ex
lib/horde/registry.ex
lib/horde/registry_impl.ex
test/cluster_test.exs

After realising I was about to re-implement it for the second time, I took a stab at creating a built-in version of [dynamic cluster membership support](https://hexdocs.pm/horde/libcluster.html#dynamic-cluster-membership). This allows the `members` option to be specified as `:auto` and uses the system described in the link above to keep cluster membership in sync with all visible nodes. It seemed like a common enough use case (and something I was mildly surprised to find was missing when I first picked up Horde) to warrant inclusion in the library itself.
I haven't written any docs for this yet - I figured I'd get some feedback first to see if you thought it was a worthwhile inclusion.

Add :auto option for cluster membership

---

lib/horde/dynamic_supervisor.ex

Hello! 👋 
This PR fixes issue #181.
Currently horde has a few typespecs errors and one of them is in the init function inside the `Horde.DynamicSupervisor`.
This fix reduces the total amount of typespec errors from 10 to 6.
To see the errors I suggest you to run dialyzer in the test environment(`MIX_ENV=test mix dialyzer`) since the tests contain code that uses the library giving more context to dialyzer. 
Thanks for you time and thank you very much for maintaining Horde! It's an awesome library! 🎉

Fix Dynamic Supervisor Init typespec - Issue #181

---

guides/getting_started.md
lib/horde/dynamic_supervisor.ex

Replaces remaining documentation references of `Horde.Supervisor` with `Horde.DynamicSupervisor`. Found this to be confusing when attempting to use `horde` for the first name.

Replace remaining references to Horder.Supervisor

---

lib/horde/registry.ex

Updates `Horde.Registry.init/1` typespec as described here https://github.com/derekkraan/horde/issues/181#issuecomment-620112186
Relates to #181

Fix Registry Init typespec - Issue #181

---

lib/horde/supervisor_telemetry_poller.ex
test/supervisor_telemetry_poller_test.exs

**In order to** avoid detachment of a poller that collects supervision metrics from Telemetry on `:EXIT` when supervisor is really busy redistributing processes, I suggest  to catch the `:EXIT` skipping a portion of metrics and log a warning.

Make collecting metrics safe

---

lib/horde/registry.ex
lib/horde/registry_impl.ex
test/registry_test.exs

[`Registry.delete_meta/2`](https://github.com/elixir-lang/elixir/pull/10298) is coming to Elixir 1.11.0 but I don't think we need to wait for 1.11.0 to be released for this feature to already land in Horde :)

Add `Horde.Registry.delete_meta/2`

---

test/supervisor_telemetry_poller_test.exs

When searching for some stuff, I found this typo 🙂

Fix typo 'failes' -> 'fails'

---

lib/horde/dynamic_supervisor_impl.ex
lib/horde/processes_supervisor.ex
test/dynamic_supervisor_deadlock_test.exs

Fixes #217
Although the actual change is only 2 LOC, the diff is rather large because I had to move the `set_child_pid` helper function down below the last `handle_cast`.

Change update_child_pid_horde to become a cast

---

lib/horde/dynamic_supervisor_impl.ex
lib/horde/table_utils.ex
test/dynamic_supervisor_test.exs
test/support/local_cluster_helper.ex

Hi, I've been using horde, in a project where I need a huge number of processes been supervised and distributed across nodes, when this number increase I note some performance degradation.. One of my guess when I inspected the DynamicSupervisorImpl were that maybe changing the maps processes_by_id and process_pid_to_id for an ETS, could have a positive effect in the performance..
Of course after the modifications, and do some tests, this change shows a improvement in the performance of spawning new childs in the supervisor, some numbers:
I tried to keep this change as local as posible thus not modifying anything outside this internal implementation detail.
I Hope this could help to enhance a bit this fantastic library.

Implement ETS's as DynamicSupervisor internal data structures instead of Maps

---

lib/horde/distribution_strategy.ex
lib/horde/dynamic_supervisor.ex
lib/horde/uniform_distribution.ex
lib/horde/uniform_quorum_distribution.ex
lib/horde/uniform_random_distribution.ex
test/uniform_random_distribution_test.exs

I added a very simple Random distribution strategy, and its test.
Most of the changes were in the ExDoc part, so that available strategies are linked from within Horde.DistributionStrategy, in the perspective of adding more in the future.
Fixes https://github.com/derekkraan/horde/issues/251 though it does not change the interface of DistributionStrategy so it's a bit more limited - but this requires a separate topic.

Added new UniformRandomDistribution strategy

---

lib/horde/registry.ex
mix.exs
test/cluster_test.exs
test/dynamic_supervisor_deadlock_test.exs
test/local_cluster_test.exs
test/netsplit_test.exs
test/network_partition_test.exs
test/support/my_supervision_tree.ex

This PR aims to remove some warnings. Also use the erpc module explicitly when possible.

Remove warnings and switch to the erpc module 

---

lib/horde/dynamic_supervisor_impl.ex
test/dynamic_supervisor_test.exs

When an existing child spec was added to the CRDT during process handoff, the old child spec is never removed from the CRDT, creating lingering child specs which results in "zombie" processes spawning when a new supervisor is started.
Fixes #262

Supervisor: old child specs remained in CRDT after process handoff

---

lib/horde/dynamic_supervisor_impl.ex
lib/horde/processes_supervisor.ex

I noticed that when a cluster is restarting, Horde tends to crash
because it does some administration that is incorrect. The child
lookup for the linked ETS table can fail but this was not handled on
all places in the Dynamic Supervisor implementation.
This fix addresses three places that resulted in crashes because nil
was not handled from the get_item / pop_item calls.
Note that there were several other places where this was already
addressed.

Fix crashes related to missing child ids in lookup table 

---

lib/horde/dynamic_supervisor.ex

The `DynamicSupervisor` was not respecting the `max_children` config when starting children as the value was not being propagated to the `ProcessesSupervisor`. This PR passes along the value so the `ProcessesSupervisor` can enforce the setting.

Pass along max_children config to ProcessesSupervisor
