bench/registry_read.exs, lib/horde/registry.ex, lib/horde/supervisor.ex, mix.exs, mix.lock, test/registry_test.exs
(to ensure that very busy systems continue to work)
=> Debounce updating list of processes & force update after 1000 updates

lib/horde/supervisor_impl.ex
This should speed up processing and make it easier to see which nodes
are in the horde.
#11
=> Just remove dead nodes from the members CRDT

.gitignore, lib/horde/process_supervisor.ex, lib/horde/uniform_distribution.ex, test/supervisor_test.exs
=> Allow Supervisor to start process with arbitrary term in childspec id

lib/horde/registry_impl.ex
- `mark_dead` was defined between two clauses of `handle_info`
- `state.members` was not defined (I used `DeltaCrdt.read(state.members_pid, 30_000)`) to retrieve members
- I also made `mark_dead` a private function
=> Fixing issues in removing dead nodes

lib/horde/registry_impl.ex
=> Remove a node from members list when it goes down

lib/horde/registry_impl.ex, test/cluster_test.exs, test/registry_test.exs
=> Fix set members registry

lib/horde/registry.ex, lib/horde/registry_impl.ex, test/registry_test.exs
=> Processes registered at a member in the cluster are ignored when that member leaves the cluster.

examples/hello_world/README.md
I think the example scaled! :) Fixing small typos
=> Adjust example

lib/horde/horde_dynamic_supervisor.ex
Sometimes when horde nodes are connected  there is a MatchError in delete_child fn
=> fix pattern match

lib/horde/registry_impl.ex, test/registry_test.exs
The exiting of the loser process caused the name registration to be removed from the CRDT entirely.
=> Fix flaw where name registration was lost entirely on conflict

lib/horde/horde_dynamic_supervisor.ex, lib/horde/supervisor_impl.ex, test/supervisor_test.exs
=> save child pid into state in order to return the correct pid on already_started error

lib/horde/registry.ex, lib/horde/registry_impl.ex, lib/horde/registry_supervisor.ex, test/registry_test.exs
=> Implement Horde.Registry :listeners option

lib/horde/registry.ex
=> Ensure Registry.child_spec/1 overridable

lib/horde/registry_impl.ex, lib/horde/supervisor_impl.ex, test/cluster_test.exs, test/registry_test.exs, test/supervisor_test.exs
Small fix. Closes https://github.com/derekkraan/horde/issues/150
I'll have a stab at adding Dialyzer here later.
=> Align `Horde.Cluster.members` with its typespec

lib/horde/processes_supervisor.ex
Dialyzer report some issues in the processes_supervisor module. This pull request should take care of them and dialyzer is happy (at least on my machine :))
=> Fix dialyzer issues in the processes supervisor

lib/horde/dynamic_supervisor.ex, lib/horde/dynamic_supervisor_impl.ex, lib/horde/registry.ex, lib/horde/registry_impl.ex, mix.exs, mix.lock
This will probably fix #166, which is probably happening because we are
storing a reference to a function and then reloading the module.
=> Use MFA tuple for on_diffs option to avoid passing functions around.

lib/horde/registry.ex
Per discussion in https://github.com/derekkraan/horde/issues/165
=> Truing up registry documentation with dynamic supervisor module

guides/eventual_consistency.md, lib/horde/dynamic_supervisor_impl.ex, lib/horde/processes_supervisor.ex, lib/horde/registry.ex, mix.exs, test/network_partition_test.exs, test/support/ignore_worker.ex, test_app/.formatter.exs, test_app/.gitignore, test_app/README.md, test_app/lib/test_app.ex, test_app/lib/test_app/application.ex, test_app/mix.exs, test_app/test/test_app_test.exs, test_app/test/test_helper.exs
=> Fix race condition

lib/horde/table_utils.ex
This PR will make use of `:ets.first` and `:ets.next` to traverse ETS and test the given predicate against entries, which should yield some performance gain over using tab2list and then iterating over the list with `Enum.any?`
=> Use a function to traverse ETS instead of using tab2list

README.md
Adding Quick Link Badge to HexDocs https://hexdocs.pm/horde
=> Add Badge to Link to HexDocs

README.md
=> Add Horde.Process link
